### PR TITLE
issue:HUDSON-8036 added support for SVN::Web

### PR DESCRIPTION
**Pull request by mvitz**
Fixes issue http://issues.hudson-ci.org/browse/HUDSON-8036

### CODE REVIEW

**Comment by christ66** [comment]
Would it be possible to get a junit to validate this works?

**Comment by mvitz** [comment]
Of course. As soon as I got it ready I will add it.

**Comment by christ66** [comment]
I'm sorry, I've been a little busy with school. I first would like to get all subversion junits passing with svnkit 1.3.7 before integrating your changes. I will merge your changes to my branch which would get merged into the hudson-plugins subversion branch in the next few weeks. I will try very hard to commit your items before Saturday night or Sunday night latest.

Thanks again,
Steve.

**Comment by wjprakash** [comment]
Steve, now that we released 2.3.2 with SVNKit 1.7 shall we merge this?

**Comment by wjprakash** [comment]
mvitz, sorry for the delay. We really appreciate the patch we provided. We did not mean to ignore it. But caught up in so many tasks we kind of postpone it. We will merge it soon.

**Comment by christ66** [comment]
Yes we can, again sorry I got caught up in a few issues. Now that I have time for this I can do the merge.

**Comment by mvitz** [comment]
No need to be sorry. I'm glad this will be in one of the next releases :-)

**Pull request merged**
